# .rubocop.yml

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  ExcludedMethods:
    - describe
    - context
    - it
